fbc: sf.net # 944: Array descriptors are defined more than once (gcc backend)
Fixes the following sequence of code when compiled with the gcc backend

dim shared A(0 to ...) as zstring ptr => { @"" }
dim shared B(0 to ...) as zstring ptr => { @"" }

sub proc( arrray() as zstring ptr )
end sub

proc( A() )
proc( B() )

'' previously this would case a gcc compile error
'' error: redefinition of 'struct $8FBARRAY1IPcE'